version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: event-booking-postgres
    environment:
      POSTGRES_DB: ticketing
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  aerospike:
    image: aerospike/aerospike-server
    container_name: event-booking-aerospike
    ports:
      - "3000:3000"

  backend:
    build: .
    container_name: event-booking-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - aerospike

volumes:
  pgdata:
